export const AUTH_RESPONSE_CODE = {
    AUTH_CREDENTIALS_NOT_VALID: "AUTH_CREDENTIALS_NOT_VALID",
    AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
    AUTH_REFRESS_SESSION_SUCCESS: "AUTH_REFRESS_SESSION_SUCCESS" 
}