export const ROL_RESPONSE_CODE = {
    ROL_EXIST: "ROL_EXIST",
    ROL_CREATED: "ROL_CREATED",
    ROL_ERROR_CREATED: "ROL_ERROR_CREATED",
    ROL_ERROR_UPDATE: "ROL_ERROR_UPDATE",
    ROL_UPDATED: "ROL_UPDATED",
    ROL_PAGINATE_SUCCESS: "ROL_PAGINATE_SUCCESS",
    ROL_FOUND: "ROL_FOUND",
    ROL_NOT_FOUND: "ROL_NOT_FOUND"
}